require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AntsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ant. As you add validations to Ant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AntsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ants as @ants" do
      ant = Ant.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ants)).to eq([ant])
    end
  end

  describe "GET #show" do
    it "assigns the requested ant as @ant" do
      ant = Ant.create! valid_attributes
      get :show, {:id => ant.to_param}, valid_session
      expect(assigns(:ant)).to eq(ant)
    end
  end

  describe "GET #new" do
    it "assigns a new ant as @ant" do
      get :new, {}, valid_session
      expect(assigns(:ant)).to be_a_new(Ant)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ant as @ant" do
      ant = Ant.create! valid_attributes
      get :edit, {:id => ant.to_param}, valid_session
      expect(assigns(:ant)).to eq(ant)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Ant" do
        expect {
          post :create, {:ant => valid_attributes}, valid_session
        }.to change(Ant, :count).by(1)
      end

      it "assigns a newly created ant as @ant" do
        post :create, {:ant => valid_attributes}, valid_session
        expect(assigns(:ant)).to be_a(Ant)
        expect(assigns(:ant)).to be_persisted
      end

      it "redirects to the created ant" do
        post :create, {:ant => valid_attributes}, valid_session
        expect(response).to redirect_to(Ant.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ant as @ant" do
        post :create, {:ant => invalid_attributes}, valid_session
        expect(assigns(:ant)).to be_a_new(Ant)
      end

      it "re-renders the 'new' template" do
        post :create, {:ant => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ant" do
        ant = Ant.create! valid_attributes
        put :update, {:id => ant.to_param, :ant => new_attributes}, valid_session
        ant.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ant as @ant" do
        ant = Ant.create! valid_attributes
        put :update, {:id => ant.to_param, :ant => valid_attributes}, valid_session
        expect(assigns(:ant)).to eq(ant)
      end

      it "redirects to the ant" do
        ant = Ant.create! valid_attributes
        put :update, {:id => ant.to_param, :ant => valid_attributes}, valid_session
        expect(response).to redirect_to(ant)
      end
    end

    context "with invalid params" do
      it "assigns the ant as @ant" do
        ant = Ant.create! valid_attributes
        put :update, {:id => ant.to_param, :ant => invalid_attributes}, valid_session
        expect(assigns(:ant)).to eq(ant)
      end

      it "re-renders the 'edit' template" do
        ant = Ant.create! valid_attributes
        put :update, {:id => ant.to_param, :ant => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ant" do
      ant = Ant.create! valid_attributes
      expect {
        delete :destroy, {:id => ant.to_param}, valid_session
      }.to change(Ant, :count).by(-1)
    end

    it "redirects to the ants list" do
      ant = Ant.create! valid_attributes
      delete :destroy, {:id => ant.to_param}, valid_session
      expect(response).to redirect_to(ants_url)
    end
  end

end
